### ISSUE TITLE
TabView icons disappear if I add a new viewController

### ISSUE THREAD

**Issue by JCassio1** [ZamzamInc/SwiftyPress#11]
Whenever I add a new viewController to the main storyboard in order to be displayed before the default tabView Controller, the icon of _Popular_ and _Explore_ simply disappear. Am I missing something that I should have done?

<img width="1280" alt="screen shot 2018-07-04 at 19 06 40" src="https://user-images.githubusercontent.com/20714698/42712611-911b71a2-86ec-11e8-9c78-7c06abd4a22a.png">

**Comment by basememara** [comment]
You should be adding the icons to the view controller storyboard, not the tab controller. Is this what you're doing?
