### ISSUE TITLE
Ambiguous subscript with base type 'UserDefaults' and index type '_'

### ISSUE THREAD

**Issue by gnh1201** [ZamzamInc/SwiftyPress#16]
`/Users/user146094/SwiftyPress/Sources/Controllers/PopularViewController.swift:41:71: Ambiguous subscript with base type 'UserDefaults' and index type '_'`

and more similarity lines:

`cell.textLabel?.textColor = UIColor(rgb: AppGlobal.userDefaults[.titleColor])`

`.titleColor` is ambiguous subscript.

**Comment by basememara** [comment]
I just finished re-writing `SwiftyPress` using Clean Architecture. Can you take a look at the `clean_arch` repo and let me know what you think? You probably want to start with the app: https://github.com/basememara/BasemEmaraBlogIOS/tree/clean_arch

It's in the store with the new look here (inspired by the new App Store and Medium apps): 
https://itunes.apple.com/app/id1021806851

**Comment by gnh1201** [comment]
clean_arch is working.
