### ISSUE TITLE
Use of undeclared type 'ZamzamKitable'

### ISSUE THREAD

**Issue by gnh1201** [ZamzamInc/SwiftyPress#18]
Error details:

/Users/user146094/SwiftyPress/Sources/AppLogger.swift:15:19: Use of undeclared type 'ZamzamKitable'

```
struct AppLogger: ZamzamKitable {

    var logFileURL: URL?
    
    init() {
```

**Comment by basememara** [comment]
I believe you have to lock `ZamzamKit` to version 1.3 in the `Cart` file.

**Comment by gnh1201** [comment]
`/Users/user146094/BasemEmaraBlogIOS/Basem Emara/Common/Styles/Themes/DarkTheme.swift:10:8: No such module 'SwiftyPress'`

**Comment by gnh1201** [comment]
I added SwiftyPress (github) to the `Cartfile`, but the SwiftyPress.framework file was not created.

**Comment by gnh1201** [comment]
https://github.com/basememara/BasemEmaraBlogIOS/tree/clean_arch

**Comment by gnh1201** [comment]
close this issue.
