### ISSUE TITLE
Could not create SwiftyPress.framework in clean_arch

### ISSUE THREAD

**Issue by gnh1201** [ZamzamInc/SwiftyPress#19]
The build was successful with clean_arch. However, the SwiftyPress.framework file is not created. Why is this?

**Comment by basememara** [comment]
The SwiftyPress project was added as a submodule to the app and dropped into the workspace. This made it easier to code in both repos faster, but I plan on adding `SwiftyPress` to the `Cartfile` eventually.

**Comment by gnh1201** [comment]
After built SwiftyPress in submodule, I was found SwiftyPress.framework in the xcode library directory.
I added this to "Frameworks" section in "Project navigator", and "Linked Frameworks and Libraries", "Embedded Binaries".
But, "No such module SwiftyPress" error was repeated. Can I find a solution?

**Comment by basememara** [comment]
The update has been merged into `master` and `develop` with `readme` instructions and a full working sample app. Please try again with the new code base and open a new issue if the issue persists. Thanks!
