### ISSUE TITLE
Carthage related Issues 

### ISSUE THREAD

**Issue by Shashikant86** [ZamzamInc/SwiftyPress#2]
Hi @basememara  Thanks for your all great efforts for this project. Its amazing. I am exactly looking for this. I was trying use `SwiftPress` but stumbled into following issues  :)  while doing 

` $ Carthage update --platform iOS ` 

* Stencil ( Carthage ) 

Stencil framework doesn't seems to be compatible with Carthage as per the docs [here](http://stencil.fuller.li/en/latest/installation.html) I need to manual go to that directory and generate Xcode project for that Swift Package . 

* Once done that Carthage is complaining with following error 

```
/Users/myProject/Carthage/Checkouts/SwiftyPress/Sources/Controllers/PostDetailViewController.swift:13:8: error: module file's minimum deployment target is ios10.2 v10.2: /Users/myProject//Carthage/Checkouts/SwiftyPress/Carthage/Build/iOS/Stencil.framework/Modules/Stencil.swiftmodule/arm64.swiftmodule
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/myProject//Carthage/Checkouts/SwiftyPress/SwiftyPress.xcworkspace -scheme "SwiftyPress iOS" -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

I have fixed that in your example app by changing deployment target to 10.2 but need to get proper fix in the framework itself so that I can use it. Also I need to know what's `post.html` file in the App?

Appreciate your help

**Comment by basememara** [comment]
Thanks for the heads up. I've been meaning to update the [readme](https://github.com/ZamzamInc/SwiftyPress/blob/master/README.md). It's a work in progress but I just uploaded it. I hope it helps in the meantime.

I had a [PR](https://github.com/kylef/Stencil/pull/65) at Stencil for Carthage support, but @kylef is pretty adamant in using Swift Package Manager purely. I see where's he's coming from, but SPM isn't compatible with iOS yet.

Eventually, I hope to script the whole project setup with templates or an Xcode extension.

**Comment by Shashikant86** [comment]
@basememara Thanks a lot for the README update. I will follow the steps but in the meantime I am trying your example app and updating `settings.plist` file with new values. I am just getting blank screen. I need to know what's `post.html` file ? but No rush.

I am looking forward to entire project as template :) that would be great step. Let me know as soon as you done it. Thanks again

**Comment by basememara** [comment]
Ah I missed your `post.html` question. It's a template to build the detail view of the blog post you're presenting. It's used to locally populate the `WKWebView` for the blog detail screen.

In `PostDetailViewController.loadTemplate()`, it is using `Stencil` to bind values to `post.html`. Since everyone's WordPress site has a different style and layout, I take a stripped down version of the WordPress template to come up with `post.html`. I think a generic Twitter Bootstrap could suffice, but will lose the branding/style of the original WordPress site. That way, the website and the mobile app look pretty close.

I hope this explains, but feel free to ask more questions from here.

**Comment by basememara** [comment]
Regarding the blank screen, do you have the app uploaded somewhere or can you post your `Settings.plist`. Also, anything in the console output regarding warnings or errors?

Could it be you don't have your `Main.storyboard` setup correctly? The view controllers should be pointing to the embedded ones from SwiftyPress.

**Comment by Shashikant86** [comment]
@basememara Thanks a lot for reply. I understood it much better and started getting my posts into app, it was Transport Layer Security missed .. I started using your files from `Frameworks` directory  an build on it in meanwhile we sort out entire framework. I really appreciate your time replying my comments :) 
Thanks again ..

**Comment by Shashikant86** [comment]
@basememara I have uploaded my project on Github [here](https://github.com/Shashikant86/XCBlog)

I am missing how to connect to ViewControllers from SwiftyPress. Can you please have a look and guide me whenever you got time ? I tried it few times and failed 

Thanks
Shashi
