### ISSUE TITLE
Support for Swift 3.1

### ISSUE THREAD

**Issue by Shashikant86** [ZamzamInc/SwiftyPress#3]
Apple has release `Swift 3.1` with Xcode 8.3. Would like to build the framework to Swift 3.1 however there are some other dependencies like `ZamzamKit`  compiled with  `Swift 3.0.1` throwing an error 

` Module compiled with 3.0.x can not be imported in the 3.1` 

It would be great if we can support for Swift 3.1 as well, no rush but worth doing it at some point before WWDC

**Comment by basememara** [comment]
Thanks for heads up, everything updated to Swift 3.1 now 👍
