### ISSUE TITLE
Type 'TestsModule' does not conform to protocol 'SwiftyPressModule'

### ISSUE THREAD

**Issue by ucelme** [ZamzamInc/SwiftyPress#30]
Hello. I downloaded and run SwiftyPress, but when try to compile it I get error: 
Type 'TestsModule' does not conform to protocol 'SwiftyPressModule'

How can I resolve it? Please, help me.

**Comment by basememara** [comment]
Can you try the latest `develop` branch, I did fix some things in that branch.
