### ISSUE TITLE
Migrate to Swift 4 

### ISSUE THREAD

**Issue by Shashikant86** [ZamzamInc/SwiftyPress#6]
@basememara Do you have any pan to migrate this project to Swift 4 ?

Or If you busy is there any way I can do it myself, may be by fork or something else ?

**Comment by basememara** [comment]
Yes I plan to updated to Swift 4 and still updating some of the dependencies first. Will keep you posted..

**Comment by Shashikant86** [comment]
👍 Thanks a lot @basememara

**Comment by basememara** [comment]
Done! e76e5b3a5b90008691688eeeca78fe2898300b65

**Comment by Shashikant86** [comment]
👍 Thanks a lot ! @basememara :)
