### ISSUE TITLE
New post notification

### ISSUE THREAD

**Issue by Rubenfer** [ZamzamInc/SwiftyPress#7]
Support this project notifications in background when new post is published in the blog? When I run the app it ask for permission for iOS Notifications, but when new post is published I don't receive the notifications.

**Comment by basememara** [comment]
I think there's something wrong with the background fetch implementation, will take a look..

**Comment by Rubenfer** [comment]
Any news on this bug?

**Comment by basememara** [comment]
The update has been merged into `master` and `develop` with `readme` instructions and a full working sample app. Please try again with the new code base and open a new issue if the issue persists. Thanks!
