### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by Rubenfer** [ZamzamInc/SwiftyPress#8]
I get the error:
Instance member 'string' cannot be used on type 'Bundle'; did you mean to use a value of this type instead?
in PostDetailViewController.swift

and

Generic type 'Result' specialized with too few type parameters (got 1, but expected 2)

**Comment by basememara** [comment]
You're right, I noticed this is related to the updates in the dependency. I will try to get this updated. In the meantime, you can lock the Carthage version in the `Cartfile`:

```
github "ZamzamInc/ZamzamKit" ~> 1.3
```

**Comment by Rubenfer** [comment]
Solved with version 1.3.

Thanks!
