### ISSUE TITLE
No such module 'ZamzamKit'

### ISSUE THREAD

**Issue by caglarturkurka** [ZamzamInc/SwiftyPress#9]
Please help me about this problem I want to use SwiftyPress for making IOS application for my wordpress web site. But When I want to run your project which was cloned, it gave error like No such module ZamzamKit. But I do not know how can I install this module.

**Comment by JCassio1** [comment]
Have you used Carthage to run the command `carthage update --platform iOS --no-build` and `(cd Carthage/Checkouts/Stencil && swift package generate-xcodeproj)`  in terminal?

**Comment by ghost** [comment]
Even after run the command `carthage update --platform iOS --no-build and (cd Carthage/Checkouts/Stencil && swift package generate-xcodeproj)` in terminal, there will be another error:

`Module compiled with Swift 4.0 cannot be imported in Swift 4.1.2: /Users/vincent-st/Downloads/SwiftyPress-master/Frameworks/realm-swift/ios/RealmSwift.framework/Modules/RealmSwift.swiftmodule/x86_64.swiftmodule`

**Comment by basememara** [comment]
This should be fixed in the latest `master` branch. The Carthage dependency had to be locked to a certain tag.

**Comment by basememara** [comment]
The update has been merged into `master` and `develop` with `readme` instructions and a full working sample app. Please try again with the new code base and open a new issue if the issue persists. Thanks!
